apiVersion: v1
kind: Service
metadata:
  name: nginx-webserver
  namespace: storage-benchmarking
spec:
  selector:
    app: fio-benchmark-testing
  ports:
    - port: 8080
      protocol: TCP
      name: http
      targetPort: 8080
