apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

nameSuffix: -pv

patches:
  - patch: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: benchmark
      spec:
        template:
          spec:
            containers:
              - name: mc-results-to-bucket
                env:
                  - name: BENCHMARK_NAME
                    value: pv
            volumes:
              - name: target
                persistentVolumeClaim:
                  claimName: benchmark-target-pvc
