apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

nameSuffix: -pv

patches:
  - patch: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: benchmark
      spec:
        template:
          spec:
            volumes:
              - name: target
                persistentVolumeClaim:
                  claimName: benchmark-target-pv
