apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-disk
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: quay.io/dystewar/fio-openshift-storage-performance:latest
          imagePullPolicy: IfNotPresent
          name: kubestr-fio-benchmark-disk
          workingDir: /target/disk
          envFrom:
            - configMapRef:
                name: storage-benchmark-results
            - secretRef:
                name: storage-benchmark-results
          command: ["/bin/sh","-c"]
          args: ["/scripts/run-benchmark.sh; /mc/mc-results-to-bucket.sh;"]
          volumeMounts:
            - mountPath: /target/disk
              name: target-disk
            - mountPath: /scripts
              name: kubestr-scripts
            - mountPath: /fio-jobs
              name: fio-jobs
            - mountPath: /mc
              name: mc-results-to-bucket
      volumes:
        - name: target-disk
          emptyDir: {}
        - name: kubestr-scripts
          configMap:
            name: run-benchmark
            defaultMode: 0777
        - name: mc-results-to-bucket
          configMap: 
            name: mc-results-to-bucket
            defaultMode: 0777
        - name: fio-jobs
          configMap: 
            name: fio-jobs
